version: '3.3'

services:
    node:
        build:
            context: ./node
            args:
                - NODE_VERSION=latest
                - PROJECT_PATH=/opt/app/
                - NODE_ENV=production
                - YARN=true
        volumes:
            - ../:/opt/app
        entrypoint: run-node "node index.js"
        tty: true

    mysql:
        build:
            context: ./mysql
            args:
                - MYSQL_DATABASE=default_database
                - MYSQL_USER=default_user
                - MYSQL_PASSWORD=secret
                - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./data/mysql/:/var/lib/mysql
        expose:
            - '3306'

    nginx:
        build:
            context: ./nginx
            args:
                - WEB_REVERSE_PROXY_PORT=8000
                - WEB_SSL=true
                - SELF_SIGNED=true
                - NO_DEFAULT=false
        volumes:
            - ./data/logs/nginx/:/var/log/nginx
            - ./certbot/certs/:/var/certs
        ports:
            - '80:80'
            - '443:443'
        tty: true

    certbot:
        build:
            context: ./certbot
        links:
            - nginx
        volumes:
            - ./certbot/letsencrypt/:/var/www/letsencrypt
            - ./certbot/certs/:/var/certs
