version: '3'
services:
  db:
    image: mysql
    networks:
      - webnet
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecommerce
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  web:
    image: ecommerce-server
    ports:
      - '4500:4500'
    depends_on:
      - db
    networks:
      - webnet
    environment:
      DB_HOST: db
    command:
      - ./wait-for-it.sh
      - 'db:5432'
      - '--'
      - node
      - index.js
networks:
  webnet: null
